---
name: on_hello_event1
pack: flow123
description: Sample rule firing on flow123.event1.
enabled: true
trigger:
    type: flow123.event1
action:
    ref: flow123.greet
    parameters:
        greeting: Yo
